project_id = "pukyiypexhscfelpkhjs"

[functions.perplexity-generate]
verify_jwt = false

[functions.perplexity-validate]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.orbis-chat]
verify_jwt = false

[functions.chat-followup]
verify_jwt = false

[functions.chat-generate]
verify_jwt = false

[functions.chat-validate]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.analyze-images]
verify_jwt = false
